# Generated by Django 4.0 on 2025-01-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_password_encrypted',
            field=models.BooleanField(default=False, verbose_name='パスワード暗号化フラグ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(limit_choices_to={'type': '部署'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_in_division', to='main.position', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(limit_choices_to={'type': '役職'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_in_position', to='main.position', verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(limit_choices_to={'type': '課'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_in_team', to='main.position', verbose_name='課'),
        ),
    ]
