# Generated by Django 4.0 on 2025-01-20 02:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.customuser')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('division', models.ForeignKey(blank=True, limit_choices_to={'type': '部署'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_in_division', to='main.position', verbose_name='部署')),
                ('position', models.ForeignKey(blank=True, limit_choices_to={'type': '役職'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_in_position', to='main.position', verbose_name='役職')),
                ('team', models.ForeignKey(blank=True, limit_choices_to={'type': '課'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_in_teasm', to='main.position', verbose_name='課')),
            ],
            options={
                'verbose_name_plural': 'スタッフ',
                'permissions': [('can_view_staff', 'Can view staff')],
                'unique_together': {('division', 'team', 'position')},
            },
            bases=('main.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='勤務日')),
                ('start_time', models.TimeField(verbose_name='勤務開始時間')),
                ('end_time', models.TimeField(verbose_name='勤務終了時間')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確定済み')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name_plural': 'シフトスケジュール',
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='希望日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name_plural': 'シフト希望',
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
    ]
