# Generated by Django 4.0 on 2025-01-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='勲章名')),
                ('description', models.TextField(verbose_name='説明')),
                ('icon', models.ImageField(upload_to='medals/icons/', verbose_name='アイコン画像')),
            ],
            options={
                'verbose_name_plural': '勲章',
            },
        ),
        migrations.CreateModel(
            name='MemberMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(verbose_name='取得日')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medal', verbose_name='勲章')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member', verbose_name='会員')),
            ],
            options={
                'verbose_name_plural': '会員勲章',
                'unique_together': {('member', 'medal')},
            },
        ),
    ]
