# Generated by Django 4.0 on 2025-01-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_shiftschedule_shiftrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ランク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ランクの説明')),
            ],
            options={
                'verbose_name_plural': 'ランク',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rank', verbose_name='ランク'),
        ),
    ]
