# Generated by Django 4.0 on 2025-01-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='売り切れフラグ'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member', verbose_name='会員')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': 'カート',
            },
        ),
    ]
