# Generated by Django 4.0 on 2025-01-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_is_sold_out_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
