# Generated by Django 4.0 on 2025-01-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='予定のタイトルを入力', max_length=255)),
                ('description', models.TextField(blank=True, help_text='予定の詳細を入力（任意）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='予定が作成された日時（自動設定）')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='予定が更新された日時（自動設定）')),
                ('is_completed', models.BooleanField(default=False, help_text='予定が完了したかどうか（デフォルトは未完了）')),
            ],
        ),
    ]
