# Generated by Django 4.0 on 2025-01-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='カテゴリ名', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='重要度レベル', max_length=20, unique=True)),
            ],
        ),
    ]
