# Generated by Django 4.0 on 2025-01-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(default=1, help_text='カテゴリを選択', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='importance',
            field=models.ForeignKey(default=1, help_text='重要度を選択', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.importance'),
            preserve_default=False,
        ),
    ]
