# Generated by Django 4.0 on 2025-01-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_schedule_category_schedule_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(default=1, upload_to='Schedule/images/', verbose_name='イメージ画像'),
            preserve_default=False,
        ),
    ]
