# Generated by Django 4.0 on 2025-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_schedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Schedule/images/', verbose_name='イメージ画像'),
        ),
    ]
