# Generated by Django 4.0 on 2025-01-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_schedule_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_day', models.DateField()),
                ('day_of_week', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
            options={
                'unique_together': {('Member', 'schedule', 'day_of_week')},
            },
        ),
    ]
