# Generated by Django 4.0 on 2025-01-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='scheduled_day',
        ),
    ]
