# Generated by Django 4.0 on 2025-01-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_userschedule_scheduled_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Event',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'スケジュール'},
        ),
        migrations.AlterModelOptions(
            name='importance',
            options={'verbose_name_plural': '重要度'},
        ),
        migrations.AlterModelOptions(
            name='userschedule',
            options={'verbose_name_plural': '曜日毎のスケジュール'},
        ),
        migrations.RenameField(
            model_name='userschedule',
            old_name='Member',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='userschedule',
            unique_together={('member', 'schedule', 'day_of_week')},
        ),
    ]
